# Generated by Django 4.2.6 on 2023-10-14 12:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password_confirmation',
            field=models.CharField(help_text='To confirm, please enter the password again.', max_length=100, validators=[django.core.validators.MinLengthValidator(3, message='The password entered is too short. It must contain at least 3 characters.')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(help_text='Required field. No more than 150 characters. Only letters, numbers and symbols @/./+/-/_.', max_length=150, unique=True),
        ),
    ]
