# Generated by Django 4.2.6 on 2023-10-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='created_at',
            field=models.DateTimeField(default='2023-10-10 12:52'),
            preserve_default=False,
        ),
    ]
