# Generated by Django 4.2.6 on 2023-10-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0004_alter_status_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='created_at',
            field=models.DateTimeField(auto_created=True, default='2023-10-12 12:52'),
            preserve_default=False,
        ),
    ]
