# Generated by Django 4.2.6 on 2023-10-23 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0006_alter_status_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='author',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
