# Generated by Django 4.2.6 on 2023-10-23 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0008_alter_status_status_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='author',
            field=models.IntegerField(max_length=150),
        ),
    ]
