# Generated by Django 4.2.6 on 2023-10-23 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0010_alter_status_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='author',
            field=models.IntegerField(blank=True),
        ),
    ]
