# Generated by Django 4.2.6 on 2023-10-23 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0012_alter_status_author_alter_status_status_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='author',
        ),
    ]
