# Generated by Django 4.2.6 on 2023-10-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='executor_fullname',
            field=models.CharField(default='namesurname', max_length=150),
            preserve_default=False,
        ),
    ]
