# Generated by Django 4.2.6 on 2023-10-29 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_task_executor_fullname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='author_fullname',
        ),
        migrations.RemoveField(
            model_name='task',
            name='executor_fullname',
        ),
        migrations.AlterField(
            model_name='task',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
    ]
