# Generated by Django 4.2.6 on 2023-10-20 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0006_task_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='author',
            field=models.ForeignKey(auto_created=True, on_delete=django.db.models.deletion.PROTECT, related_name='auth', to=settings.AUTH_USER_MODEL),
        ),
    ]
